sudo: false

language: node_js

node_js:
  - "8"
  - "10"
  - "12"

before_install:
  - gem update --system
  - gem install sass

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
