clone_depth: 10

version: "{build}"

# What combinations to test
environment:
  matrix:
    - nodejs_version: "8"
      platform: x86
      ruby_folder_version: "23"
    - nodejs_version: "10"
      platform: x86
      ruby_folder_version: "23"
    - nodejs_version: "12"
      platform: x86
      ruby_folder_version: "23"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - SET "PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%"
  - gem install sass
  - npm install

test_script:
  # Output useful info for debugging
  - node --version && npm --version
  - ruby --version && gem --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
